aave-v1-pools: # https://app-v1.aave.com
  contracts: # https://docs.aave.com/developers/v/1.0/deployed-contracts/deployed-contract-instances
    - 0x398eC7346DcD622eDc5ae82352F02bE94C62d119
  events:
    - event Deposit(address indexed _reserve,address indexed _user,uint256 _amount,uint16 indexed _referral,uint256 _timestamp)
    - event RedeemUnderlying(address indexed _reserve,address indexed _user,uint256 _amount,uint256 _timestamp)
    - event Borrow(address indexed _reserve,address indexed _user,uint256 _amount,uint256 _borrowRateMode,uint256 _borrowRate,uint256 _originationFee,uint256 _borrowBalanceIncrease,uint16 indexed _referral,uint256 _timestamp)
    - event Repay(address indexed _reserve,address indexed _user,address indexed _repayer,uint256 _amountMinusFees,uint256 _fees,uint256 _borrowBalanceIncrease,uint256 _timestamp)
    - event Swap(address indexed _reserve,address indexed _user,uint256 _newRateMode,uint256 _newRate,uint256 _borrowBalanceIncrease,uint256 _timestamp)
    - event ReserveUsedAsCollateralEnabled(address indexed _reserve, address indexed _user)
    - event ReserveUsedAsCollateralDisabled(address indexed _reserve, address indexed _user)
    - event RebalanceStableBorrowRate(address indexed _reserve,address indexed _user,uint256 _newStableRate,uint256 _borrowBalanceIncrease,uint256 _timestamp)
    - event FlashLoan(address indexed _target,address indexed _reserve,uint256 _amount,uint256 _totalFee,uint256 _protocolFee,uint256 _timestamp)
    - event LiquidationCall(address indexed _collateral,address indexed _reserve,address indexed _user,uint256 _purchaseAmount,uint256 _liquidatedCollateralAmount,uint256 _accruedBorrowInterest,address _liquidator,bool _receiveAToken,uint256 _timestamp)
aave-v1-tokens:
  contracts: # https://docs.aave.com/developers/v/1.0/deployed-contracts/deployed-contract-instances
    - 0x3a3A65aAb0dd2A17E3F1947bA16138cd37d08c04 # aETH
    - 0xfC1E690f61EFd961294b3e1Ce3313fBD8aa4f85d # aDAI
    - 0x9bA00D6856a4eDF4665BcA2C2309936572473B7E # aUSDC
    - 0x625aE63000f46200499120B906716420bd059240 # aSUSD
    - 0x4da9b813057d04baef4e5800e36083717b4a0341 # aTUSD
    - 0x71fc860F7D3A592A4a98740e39dB31d25db65ae8 # aUSDT
    - 0x6Ee0f7BB50a54AB5253dA0667B0Dc2ee526C30a8 # aBUSD
    - 0xe1ba0fb44ccb0d11b80f92f4f8ed94ca3ff51d00 # aBAT
    - 0x712DB54daA836B53Ef1EcBb9c6ba3b9Efb073F40 # aENJ
    - 0x9D91BE44C06d373a8a226E1f3b146956083803eB # aKNC
    - 0xba3D9687Cf50fE253cd2e1cFeEdE1d6787344Ed5 # aAAVE
    - 0xA64BD6C70Cb9051F6A9ba1F163Fdc07E0DfB5F84 # aLINK
    - 0x6FCE4A401B6B80ACe52baAefE4421Bd188e76F6f # aMANA
    - 0x7deB5e830be29F91E298ba5FF1356BB7f8146998 # aMKR
    - 0x69948cC03f478B95283F7dbf1CE764d0fc7EC54C # aREM
    - 0x71010A9D003445aC60C4e6A7017c1E89A477B438 # aREP
    - 0x328C4c80BC7aCa0834Db37e6600A6c49E12Da4DE # aSNX
    - 0xB124541127A0A657f056D9Dd06188c4F1b0e5aab # aUNI
    - 0xFC4B8ED459e00e5400be803A9BB3954234FD50e3 # aWBTC
    - 0x12e51E77DAAA58aA0E9247db7510Ea4B46F9bEAd # aYFI
    - 0x6Fb0855c404E09c47C3fBCA25f08d4E41f9F062f # aZRX
    - 0x7D2D3688Df45Ce7C552E19c27e007673da9204B8 # aLEND
  events: # https://github.com/aave/aave-protocol/blob/4b4545fb583fd4f400507b10f3c3114f45b8a037/contracts/tokenization/AToken.sol
    - Transfer (address indexed from, address indexed to, uint256 value)
    - Approval (address indexed owner, address indexed spender, uint256 value)
    - event Redeem(address indexed _from,uint256 _value,uint256 _fromBalanceIncrease,uint256 _fromIndex);
    - event MintOnDeposit(address indexed _from,uint256 _value,uint256 _fromBalanceIncrease,uint256 _fromIndex);
    - event BurnOnLiquidation(address indexed _from,uint256 _value,uint256 _fromBalanceIncrease,uint256 _fromIndex);
    - event BalanceTransfer(address indexed _from,address indexed _to,uint256 _value,uint256 _fromBalanceIncrease,uint256 _toBalanceIncrease,uint256 _fromIndex,uint256 _toIndex);
    - event InterestStreamRedirected(address indexed _from,address indexed _to,uint256 _redirectedBalance,uint256 _fromBalanceIncrease,uint256 _fromIndex);
    - event RedirectedBalanceUpdated(address indexed _targetAddress,uint256 _targetBalanceIncrease,uint256 _targetIndex,uint256 _redirectedBalanceAdded,uint256 _redirectedBalanceRemoved);
    - event InterestRedirectionAllowanceChanged(address indexed _from,address indexed _to);
aave-v2-pools:
  contracts: # https://docs.aave.com/developers/v/2.0/deployed-contracts/deployed-contracts
    - 0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9
  events: # https://github.com/aave/protocol-v2/blob/baeb455fad42d3160d571bd8d3a795948b72dd85/contracts/interfaces/ILendingPool.sol
    - event Repay (address indexed reserve, address indexed user, address indexed repayer, uint256 amount)
    - event Withdraw(address indexed reserve, address indexed user, address indexed to, uint256 amount)
    - event Borrow(address indexed reserve,address user,address indexed onBehalfOf,uint256 amount,uint256 borrowRateMode,uint256 borrowRate,uint16 indexed referral)
    - event Deposit(address indexed reserve,address user,address indexed onBehalfOf,uint256 amount,uint16 indexed referral)
    - event Swap(address indexed reserve, address indexed user, uint256 rateMode)
    - event ReserveUsedAsCollateralEnabled(address indexed reserve, address indexed user)
    - event ReserveUsedAsCollateralDisabled(address indexed reserve, address indexed user)
    - event RebalanceStableBorrowRate(address indexed reserve, address indexed user)
    - event FlashLoan(address indexed target,address indexed initiator,address indexed asset,uint256 amount,uint256 premium,uint16 referralCode)
    - event ReserveDataUpdated(address indexed reserve,uint256 liquidityRate,uint256 stableBorrowRate,uint256 variableBorrowRate,uint256 liquidityIndex,uint256 variableBorrowIndex)
    - event LiquidationCall(address indexed collateralAsset,address indexed debtAsset,address indexed user,uint256 debtToCover,uint256 liquidatedCollateralAmount,address liquidator,bool receiveAToken)
# TODO: fill according to https://docs.aave.com/developers/v/2.0/deployed-contracts/deployed-contracts
aave-v2-tokens: # TODO: ATokens, stable-debt, var-debt
  contracts: []
  events:
    - Transfer (address indexed from, address indexed to, uint256 value)
    - Approval (address indexed owner, address indexed spender, uint256 value)
# aave-v3: # omit it
