compound-v2-pools: # https://docs.compound.finance/v2/
  contracts:
    - 0x3FDA67f7583380E67ef93072294a7fAc882FD7E7 # Comptroller
  events:
    - SupplyWithdrawn (address account, address asset, uint256 amount, uint256 startingBalance, uint256 newBalance)
    - SupplyReceived(address account, address asset, uint amount, uint startingBalance, uint newBalance)
    - BorrowTaken(address account, address asset, uint amount, uint startingBalance, uint borrowAmountWithFee, uint newBalance)
    - BorrowRepaid(address account, address asset, uint amount, uint startingBalance, uint newBalance)
    - BorrowLiquidated(address targetAccount,address assetBorrow,uint borrowBalanceBefore,uint borrowBalanceAccumulated,uint amountRepaid,uint borrowBalanceAfter,address liquidator,address assetCollateral,uint collateralBalanceBefore,uint collateralBalanceAccumulated,uint amountSeized,uint collateralBalanceAfter)
    - EquityWithdrawn(address asset, uint equityAvailableBefore, uint amount, address owner)
    - AccrueInterest (uint256 interestAccumulated, uint256 borrowIndex, uint256 totalBorrows)
    - Redeem (address redeemer, uint256 redeemAmount, uint256 redeemTokens)
    - Borrow (address borrower, uint256 borrowAmount, uint256 accountBorrows, uint256 totalBorrows)
    - RepayBorrow (address payer, address borrower, uint256 repayAmount, uint256 accountBorrows, uint256 totalBorrows)
    - LiquidateBorrow(address liquidator, address borrower, uint repayAmount, address cTokenCollateral, uint seizeTokens)
    - DistributedSupplierComp ( address indexed cToken, address indexed supplier, uint256 compDelta, uint256 compSupplyIndex)
compound-v2-tokens:
  contracts:
    - 0xe65cdB6479BaC1e22340E4E755fAE7E509EcD06c # cAAVE
    - 0x6C8c6b02E7b2BE14d4fA6022Dfd6d75921D90E4E # cBAT
    - 0x70e36f6BF80a52b3B46b3aF8e106CC0ed743E8e4 # cCOMP
    - 0x5d3a536E4D6DbD6114cc1Ead35777bAB948E3643 # cDAI
    - 0x4Ddc2D193948926D02f9B1fE9e1daa0718270ED5 # cETH
    - 0x7713DD9Ca933848F6819F38B8352D9A15EA73F67 # cFEI
    - 0xFAce851a4921ce59e912d19329929CE6da6EB0c7 # cLINK
    - 0x95b4eF2869eBD94BEb4eEE400a99824BF5DC325b # cMKR
    - 0x158079Ee67Fce2f58472A96584A73C7Ab9AC95c1 # cREP
    - 0xF5DCe57282A584D2746FaF1593d3121Fcac444dC # cSAI
    - 0x4B0181102A0112A2ef11AbEE5563bb4a3176c9d7 # cSUSHI
    - 0x12392F67bdf24faE0AF363c24aC620a2f67DAd86 # cTUSD
    - 0x35A18000230DA775CAc24873d00Ff85BccdeD550 # cUNI
    - 0x39AA39c021dfbaE8faC545936693aC917d5E7563 # cUSDC 
    - 0x041171993284df560249B57358F931D9eB7b925D # cUSDP
    - 0xf650C3d88D12dB855b8bf7D11Be6C55A4e07dCC9 # cUSDT
    - 0xC11b1268C1A384e55C48c2391d8d480264A3A7F4 # cWBTC
    - 0xccF4429DB6322D5C611ee964527D42E5d685DD6a # cWBTC2
    - 0x80a2AE356fc9ef4305676f7a3E2Ed04e12C33946 # cYFI
    - 0xB3319f5D18Bc0D84dD1b4825Dcde5d5f7266d407 # cZRX
    - 0xc00e94Cb662C3520282E6f5717214004A7f26888 # COMP
  events:
    - Transfer (address indexed from, address indexed to, uint256 value)
    - Approval (address indexed owner, address indexed spender, uint256 value)
# Compound-v2-Governance:
#   contracts:
#     - 0xc0Da02939E1441F497fd74F78cE7Decb17B66529
#   events: # https://github.com/compound-finance/compound-protocol/blob/master/contracts/Governance/GovernorBravoInterfaces.sol
#     - event ProposalCreated(uint id, address proposer, address[] targets, uint[] values, string[] signatures, bytes[] calldatas, uint startBlock, uint endBlock, string description);
#     - event VoteCast(address indexed voter, uint proposalId, uint8 support, uint votes, string reason); # An event emitted when a vote has been cast on a proposal
#     - event ProposalCanceled(uint id); # An event emitted when a proposal has been canceled
#     - event ProposalQueued(uint id, uint eta); # An event emitted when a proposal has been queued in the Timelock
#     - event ProposalExecuted(uint id); # An event emitted when a proposal has been executed in the Timelock
#     - event VotingDelaySet(uint oldVotingDelay, uint newVotingDelay); # An event emitted when the voting delay is set
#     - event VotingPeriodSet(uint oldVotingPeriod, uint newVotingPeriod); # An event emitted when the voting period is set
#     - event NewImplementation(address oldImplementation, address newImplementation); # Emitted when implementation is changed
#     - event ProposalThresholdSet(uint oldProposalThreshold, uint newProposalThreshold); # Emitted when proposal threshold is set    
#     - event NewPendingAdmin(address oldPendingAdmin, address newPendingAdmin); # Emitted when pendingAdmin is changed
#     - event NewAdmin(address oldAdmin, address newAdmin); # Emitted when pendingAdmin is accepted, which means admin is updated
#     - event WhitelistAccountExpirationSet(address account, uint expiration); # Emitted when whitelist account expiration is set
#     - event WhitelistGuardianSet(address oldGuardian, address newGuardian); # Emitted when the whitelistGuardian is set
compound-v3-pools: # https://github.com/compound-finance/comet
  contracts:
    - 0xc3d688B66703497DAA19211EEdff47f25384cdc3 # cUSDCv3
    - 0xA17581A9E3356d9A858b789D68B4d866e593aE94 # cWETHv3
  events: # https://github.com/compound-finance/comet/blob/main/contracts/CometMainInterface.sol
    - event Supply(address indexed from, address indexed dst, uint amount);
    - event Transfer(address indexed from, address indexed to, uint amount);
    - event Withdraw(address indexed src, address indexed to, uint amount);
    - event SupplyCollateral(address indexed from, address indexed dst, address indexed asset, uint amount);
    - event TransferCollateral(address indexed from, address indexed to, address indexed asset, uint amount);
    - event WithdrawCollateral(address indexed src, address indexed to, address indexed asset, uint amount);
    - event AbsorbDebt(address indexed absorber, address indexed borrower, uint basePaidOut, uint usdValue); # Event emitted when a borrow position is absorbed by the protocol
    - event AbsorbCollateral(address indexed absorber, address indexed borrower, address indexed asset, uint collateralAbsorbed, uint usdValue); # Event emitted when a user's collateral is absorbed by the protocol
    - event BuyCollateral(address indexed buyer, address indexed asset, uint baseAmount, uint collateralAmount); # Event emitted when a collateral asset is purchased from the protocol
    - event PauseAction(bool supplyPaused, bool transferPaused, bool withdrawPaused, bool absorbPaused, bool buyPaused); # Event emitted when an action is paused/unpaused
    - event WithdrawReserves(address indexed to, uint amount); # Event emitted when reserves are withdrawn by the governor
# compound-v3-Configurator: # some admin opeartions
#   contracts:
#     - 0x316f9708bB98af7dA9c68C1C3b5e79039cD336E3 # for both USDC & WETH
#   events:
#     - event AddAsset(address indexed cometProxy, AssetConfig assetConfig);
#     - event CometDeployed(address indexed cometProxy, address indexed newComet);
#     - event GovernorTransferred(address indexed oldGovernor, address indexed newGovernor);
#     - event SetFactory(address indexed cometProxy, address indexed oldFactory, address indexed newFactory);
#     - event SetGovernor(address indexed cometProxy, address indexed oldGovernor, address indexed newGovernor);
#     - event SetConfiguration(address indexed cometProxy, Configuration oldConfiguration, Configuration newConfiguration);
#     - event SetPauseGuardian(address indexed cometProxy, address indexed oldPauseGuardian, address indexed newPauseGuardian);
#     - event SetBaseTokenPriceFeed(address indexed cometProxy, address indexed oldBaseTokenPriceFeed, address indexed newBaseTokenPriceFeed);
#     - event SetExtensionDelegate(address indexed cometProxy, address indexed oldExt, address indexed newExt);
#     - event SetSupplyKink(address indexed cometProxy,uint64 oldKink, uint64 newKink);
#     - event SetSupplyPerYearInterestRateSlopeLow(address indexed cometProxy,uint64 oldIRSlopeLow, uint64 newIRSlopeLow);
#     - event SetSupplyPerYearInterestRateSlopeHigh(address indexed cometProxy,uint64 oldIRSlopeHigh, uint64 newIRSlopeHigh);
#     - event SetSupplyPerYearInterestRateBase(address indexed cometProxy,uint64 oldIRBase, uint64 newIRBase);
#     - event SetBorrowKink(address indexed cometProxy,uint64 oldKink, uint64 newKink);
#     - event SetBorrowPerYearInterestRateSlopeLow(address indexed cometProxy,uint64 oldIRSlopeLow, uint64 newIRSlopeLow);
#     - event SetBorrowPerYearInterestRateSlopeHigh(address indexed cometProxy,uint64 oldIRSlopeHigh, uint64 newIRSlopeHigh);
#     - event SetBorrowPerYearInterestRateBase(address indexed cometProxy,uint64 oldIRBase, uint64 newIRBase);
#     - event SetStoreFrontPriceFactor(address indexed cometProxy, uint64 oldStoreFrontPriceFactor, uint64 newStoreFrontPriceFactor);
#     - event SetBaseTrackingSupplySpeed(address indexed cometProxy, uint64 oldBaseTrackingSupplySpeed, uint64 newBaseTrackingSupplySpeed);
#     - event SetBaseTrackingBorrowSpeed(address indexed cometProxy, uint64 oldBaseTrackingBorrowSpeed, uint64 newBaseTrackingBorrowSpeed);
#     - event SetBaseMinForRewards(address indexed cometProxy, uint104 oldBaseMinForRewards, uint104 newBaseMinForRewards);
#     - event SetBaseBorrowMin(address indexed cometProxy, uint104 oldBaseBorrowMin, uint104 newBaseBorrowMin);
#     - event SetTargetReserves(address indexed cometProxy, uint104 oldTargetReserves, uint104 newTargetReserves);
#     - event UpdateAsset(address indexed cometProxy, AssetConfig oldAssetConfig, AssetConfig newAssetConfig);
#     - event UpdateAssetPriceFeed(address indexed cometProxy, address indexed asset, address oldPriceFeed, address newPriceFeed);
#     - event UpdateAssetBorrowCollateralFactor(address indexed cometProxy, address indexed asset, uint64 oldBorrowCF, uint64 newBorrowCF);
#     - event UpdateAssetLiquidateCollateralFactor(address indexed cometProxy, address indexed asset, uint64 oldLiquidateCF, uint64 newLiquidateCF);
#     - event UpdateAssetLiquidationFactor(address indexed cometProxy, address indexed asset, uint64 oldLiquidationFactor, uint64 newLiquidationFactor);
#     - event UpdateAssetSupplyCap(address indexed cometProxy, address indexed asset, uint128 oldSupplyCap, uint128 newSupplyCap);
compound-v3-tokens: # all simple ERC20
  contracts:
    # TokenUSDC
    - 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48 # USDC
    - 0xc00e94Cb662C3520282E6f5717214004A7f26888 # COMP (same to v2)
    - 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599 # WBTC
    - 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 # WTEH
    - 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984 # UNI
    - 0x514910771AF9Ca656af840dff83E8264EcF986CA # LINK
    # TokenWETH
    - 0xBe9895146f7AF43049ca1c1AE358B0541Ea49704 # cbETH
    - 0x7f39C581F595B53c5cb19bD0b3f8dA6c935E2Ca0 # wstETH
    - 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 # WETH
  events:
    - event Transfer(address indexed from, address indexed to, uint amount);
