# https://github.com/dforce-network/LendingContractsV2/blob/master/DeployedAddresses.md
dForce-controller:
  contracts:
    - 0x8B53Ab2c0Df3230EA327017C91Eb909f815Ad113 # Controller
  events: # https://github.com/dforce-network/LendingContractsV2, all admin event omitted
    - event MarketEntered(address iToken, address account); # Emitted when an account enters a market
    - event MarketExited(address iToken, address account); # Emitted when an account exits a market
    - event BorrowedAdded(address iToken, address account); # Emitted when an account add a borrow asset
    - event BorrowedRemoved(address iToken, address account); # Emitted when an account remove a borrow asset
dForce-rewardDistributor:
  contracts:
    - 0x03E3E97C8bff9549FAc5CBfAce5Cd13E0Abe0A92
  events: # https://github.com/dforce-network/LendingContractsV2/blob/master/contracts/interface/IRewardDistributorV3.sol
    - event RewardDistributed(address iToken, address account, uint256 amount, uint256 accountIndex);
dForce-MSDController: # Multicurrency Stable Debt
  contracts:
    - 0x45677a101D70E9910C418D9426bC6c5874CE2Fd7
  events:
    - event MSDEarningAdded(address token,address minter,uint256 earning,uint256 totalEarning); # Emitted when `token`'s earning is added by `minter`.
    - event MSDDebtAdded(address token,address minter,uint256 debt,uint256 totalDebt); #  Emitted when `token`'s debt is added by `minter`.
    - event ReservesWithdrawn(address owner,address token,uint256 amount,uint256 oldTotalReserves,uint256 newTotalReserves);
dForce-MSDS:
  contracts:
    - 0xE3ec7De9375bFc22F4481C4605431d67ED5Bd260 # MSDS
  events:
    - Transfer (address indexed from, address indexed to, uint256 value)
    - Approval (address indexed owner, address indexed spender, uint256 value)
dForce-tokens: # include iMSD
  contracts:
    - 0x5812fCF91adc502a765E5707eBB3F36a07f63c02 # iWBTC
    - 0x5ACD75f21659a59fFaB9AEBAf350351a8bfaAbc0 # iETH
    - 0x1180c114f7fAdCB6957670432a3Cf8Ef08Ab5354 # iUSDT
    - 0x2f956b2f801c6dad74E87E7f45c94f6283BF0f45 # iUSDC
    - 0x298f243aD592b6027d4717fBe9DeCda668E3c3A8 # iDai
    - 0x24677e213DeC0Ea53a430404cF4A11a6dc889FCe # iBUSD
    - 0x47566acD7af49D2a192132314826ed3c3c5f3698 # iHBTC
    - 0xb3dc7425e63E1855Eb41107134D471DD34d7b239 # iDF
    - 0x164315EA59169D46359baa4BcC6479bB421764b6 # iGOLDx
    - 0x8F70B274847418618D66e651437d5Fb24d0F605b # iMSD
  events:
    # https://github.com/dforce-network/LendingContractsV2/blob/master/contracts/TokenBase/TokenEvent.sol User Events onlyk
    - UpdateInterest (uint256 currentBlockNumber, uint256 interestAccumulated, uint256 borrowIndex, uint256 cash, uint256 totalBorrows, uint256 totalReserves)
    - Mint (address sender, address recipient, uint256 mintAmount, uint256 mintTokens)
    - Redeem (address from, address recipient, uint256 redeemiTokenAmount, uint256 redeemUnderlyingAmount)
    - Borrow (address borrower, uint256 borrowAmount, uint256 accountBorrows, uint256 accountInterestIndex, uint256 totalBorrows) # Emits when underlying is borrowed.
    - RepayBorrow (address payer, address borrower, uint256 repayAmount, uint256 accountBorrows, uint256 accountInterestIndex, uint256 totalBorrows)
    - LiquidateBorrow (address liquidator, address borrower, uint256 repayAmount, address iTokenCollateral, uint256 seizeTokens)
    - event Flashloan(address loaner, uint256 loanAmount,uint256 flashloanFee,uint256 protocolFee,uint256 timestamp);
    - Transfer (address indexed from, address indexed to, uint256 value)
    - Approval (address indexed owner, address indexed spender, uint256 value)
