Morpho:
  contracts:
    - 0x777777c9898D384F785Ee44Acfe945efDFf5f3E0 # Morpho AAVE v2
    - 0x8888882f8f843896699869179fB6E4f7e3B58888 # Morpho Compound
  events: # https://developers.morpho.xyz/event-and-lenses/events
    - event Supplied(address indexed _supplier,address indexed _onBehalf,address indexed _poolTokenAddress,uint256 _amount,uint256 _balanceOnPool,uint256 _balanceInP2P);
    - event Borrowed(address indexed _user,address indexed _poolTokenAddress,uint256 _amount,uint256 _balanceOnPool,uint256 _balanceInP2P);
    - event Withdrawn(address indexed _supplier,address indexed _receiver,address indexed _poolTokenAddress,uint256 _amount,uint256 _balanceOnPool,uint256 _balanceInP2P);
    - event Repaid(address indexed _repayer,address indexed _onBehalf,address indexed _poolTokenAddress,uint256 _amount,uint256 _balanceOnPool,uint256 _balanceInP2P);
    - event Liquidated(address _liquidator,address indexed _liquidated,address indexed _poolTokenBorrowedAddress,uint256 _amountRepaid,address indexed _poolTokenCollateralAddress,uint256 _amountSeized);
    - event SupplierPositionUpdated(address indexed _user,address indexed _poolTokenAddress,uint256 _balanceOnPool,uint256 _balanceInP2P);
    - event BorrowerPositionUpdated(address indexed _user,address indexed _poolTokenAddress,uint256 _balanceOnPool,uint256 _balanceInP2P);
    - event P2PSupplyDeltaUpdated(address indexed _poolTokenAddress,uint256 _p2pSupplyDelta);
    - event P2PBorrowDeltaUpdated(address indexed _poolTokenAddress,uint256 _p2pBorrowDelta);
# Morpho-Lens: # The admin contract, useless
#   - 0x507fA343d0A90786d86C7cd885f5C49263A91FF4 # AAVE v2
#   - 0x930f1b46e1d081ec1524efd95752be3ece51ef67 # Compound
# Morpho_AAVE-Token:
#   contracts:
#     - 0x9994E35Db50125E0DF82e4c2dde62496CE330999 # this is the layer1 $MORPHO Token, shouldnt appear here
#   events:
#     - Transfer (address indexed from, address indexed to, uint256 value)
#     - Approval (address indexed owner, address indexed spender, uint256 value)
# Morpho_Compound-Token:
#   contracts:
#     - 0x9994E35Db50125E0DF82e4c2dde62496CE330999
#   events:
#     - Transfer (address indexed from, address indexed to, uint256 value)
#     - Approval (address indexed owner, address indexed spender, uint256 value)
    # TODO:
    # - Deposit
    # - Withdraw
    # - OwnershipTransferred
    # - Initialized