Sturdy: # TODO
  contracts:
    - 0xA422CA380bd70EeF876292839222159E41AAEe17
  events:
    - Deposit(address indexed reserve,address user,address indexed onBehalfOf,uint256 amount,uint16 indexed referral)
    - Deposit(address indexed sender, address indexed owner, uint256 assets, uint256 shares)
    - DepositCollateral(address indexed collateralAsset, address indexed from, uint256 amount)
    - Withdraw(address indexed reserve, address indexed user, address indexed to, uint256 amount)
    - RedeemUnderlying(address indexed _reserve,address indexed _user,uint256 _amount,uint256 _timestamp)
    - Borrow(address indexed _reserve,address indexed _user,uint256 _amount,uint256 _borrowRateMode,uint256 _borrowRate,uint256 _originationFee,uint256 _borrowBalanceIncrease,uint16 indexed _referral,uint256 _timestamp)
    - Repay(address indexed _reserve,address indexed _user,address indexed _repayer,uint256 _amountMinusFees,uint256 _fees,uint256 _borrowBalanceIncrease,uint256 _timestamp)
    - Repay(address indexed reserve, address indexed user, address indexed repayer, uint256 amount)
    - Swap(address indexed _reserve,address indexed _user,uint256 _newRateMode,uint256 _newRate,uint256 _borrowBalanceIncrease,uint256 _timestamp)
    - ReserveUsedAsCollateralEnabled(address indexed _reserve, address indexed _user)
    - ReserveUsedAsCollateralDisabled(address indexed _reserve, address indexed _user)
    - RebalanceStableBorrowRate(address indexed _reserve,address indexed _user,uint256 _newStableRate,uint256 _borrowBalanceIncrease,uint256 _timestamp)
    - FlashLoan(address indexed _target,address indexed _reserve,uint256 _amount,uint256 _totalFee,uint256 _protocolFee,uint256 _timestamp)
    - OriginationFeeLiquidated(address indexed _collateral,address indexed _reserve,address indexed _user,uint256 _feeLiquidated,uint256 _liquidatedCollateralForFee,uint256 _timestamp)
    - LiquidationCall(address indexed _collateral,address indexed _reserve,address indexed _user,uint256 _purchaseAmount,uint256 _liquidatedCollateralAmount,uint256 _accruedBorrowInterest,address _liquidator,bool _receiveAToken,uint256 _timestamp)
Sturdy-Token:
  contracts:
    - 0x51D5c5D784334a4b52a07AC13D9db79cBefa1642
    - 0xE408768fc65116143E1F65Ff9356cD0De6868fCc
    - 0x6BF4f9C7Bf935A5742324DC4BfE32F5c68B86028
  events:
    - Transfer(address indexed from, address indexed to, uint256 value)
    - Approval (address indexed owner, address indexed spender, uint256 value)
